// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qovjzlvrockykpwrlzaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvdmp6bHZyb2NreWtwd3JsemF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTM3OTksImV4cCI6MjA3NDI4OTc5OX0.qfiau8TYfBGus8lQcj5LBSaL5StKpH5QYemamXEOgzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});